### PR TITLE
Reorganize recursive soft drop code + some other updates

### PR DESCRIPTION
**Pull request by mverwe**
-- Cleanup of include/softDropGroomer.hh moving everything unrelated to 1st prong grooming to other classes (see below).
-- Recursive SD + variables that were being stored in softDropGroomer now in include/softDropCounter.hh
-- example for how to use groomer and counter can be found in runSoftDrop.cc
-- calculation of jet profiles in its own class: include/jetProfile.hh
-- adjusted runJetProfile.cc to the changes above. toy model is gone
-- added storing of initial partons in runCreatePythia.cc + corresponding changes to include/pythiaEvent.hh
-- added script to generate Vincia events (script that makes Makefile checks itself if Vincia is available)
-- ported Yi's version of include/treeWriter.hh and include/jetCollection.hh to support double vector

@FHead @kagarner @aontoso @lcunquei : please check and let me know if something is missing / wrong / etc...

### CODE REVIEW

**Comment by mverwe** [comment]
no comments? can I merge this?

**Comment by aontoso** [comment]
Hey Marta,

For the Recursive Soft Drop studies I have added some functions to calculate the formation time and things like this in the softDropCounter.hh. Don’t know if this will be useful or people prefer to do the analysis in a different way. It might be also a good time to add the GridSubtraction file that I didn’t manage to push myself and not feel confident enough to try again. I know sending files is not the best way to do things but right now I don’t see an alternative..

Best,
Alba

Alba Soto Ontoso, Ph.D
Post-Doctoral Research Associate,
Brookhaven National Lab
+1(631) 344-8953

On Jun 25, 2019, at 7:55 AM, Marta Verweij <notifications@github.com<mailto:notifications@github.com>> wrote:


no comments? can I merge this?

**Comment by mverwe** [comment]
Hi Alba,

the implementation of the grid subtractor is independent from all these changes so is best to do in a separate pull request (if you don't know how-to let me know).

For the changes in softDropCounter: did you start from my new version? where can we see it?

**Comment by aontoso** [comment]
My changes are in the file that I attached in my previous email. I didn’t start from your new version so will check that today


On Jun 25, 2019, at 9:54 AM, Marta Verweij <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Alba,

the implementation of the grid subtractor is independent from all these changes so is best to do in a separate pull request (if you don't know how-to let me know).

For the changes in softDropCounter: did you start from my new version? where can we see it?

**Comment by mverwe** [comment]
@aontoso: I’m afraid your attachment is being stripped off. If it is in your repo, just send me a link and I’ll take care of it

**Comment by kagarner** [comment]
Hi Marta,

sorry for the late answer!

I feel that the code for the declustering via the Lund Plane (e.g. RecursiveParents in softDropGroomer.hh) has disappeared. Or do I overlook it? As I understand, you want to shift this part to the new file jetProfile.hh? To my opinion, this is a good chance to restructure the code and tidy up. So, I would propose you continue merging your commit and then Leticia and I are shifting everything that is needed to the new file. 

Best,
Katharina

**Comment by mverwe** [comment]
Hi Katharina,

The code that does the recursive analysis was indeed moved moved away from softDropGroomer. It's now in softDropCounter.hh. jetProfile.hh contains the code to calculate jet profiles that I found in your edits.

**Comment by aontoso** [comment]
Here you are:
https://github.com/aontoso/JetToyHI/blob/master/include/softDropCounter.hh
https://github.com/aontoso/JetToyHI/blob/master/include/gridSubtractor.hh

Alba Soto Ontoso, Ph.D
Post-Doctoral Research Associate,
Brookhaven National Lab
+1(631) 344-8953

On Jun 26, 2019, at 3:17 AM, Marta Verweij <notifications@github.com<mailto:notifications@github.com>> wrote:


@aontoso<https://github.com/aontoso>: I’m afraid your attachment is being stripped off. If it is in your repo, just send me a link and I’ll take care of it

**Comment by mverwe** [comment]
I'm merging this so that we can continue with the other improvements as discussed above in separate PRs

**Comment by kagarner** [comment]
> Hi Katharina,
> 
> The code that does the recursive analysis was indeed moved moved away from softDropGroomer. It's now in softDropCounter.hh. jetProfile.hh contains the code to calculate jet profiles that I found in your edits.

Hi Marta,
okay thanks, now I see! Then, everything looks very nice.

**Pull request merged**
