### PR TITLE
add gridSubtractor from Alba

### PR DESCRIPTION
**Pull request by mverwe**
@aontoso :
Here goes your gridSubtractor. I added also an example on how to run in runJewelSub.cc (not tested because I didn't have a JEWEL recoil file handy). Please, check if this is how you intended it.

Note: compiler spits out a warning that etaMin_ and phiMin_ are not used. It seems in the code a symmetric acceptance is assumed. Shall we fix this?

@rkunnawa

### CODE REVIEW

**Review by aontoso — COMMENTED** [review]
The output of the gridSubtractor is a collection of particles so I usually used it as follows.

First, find thee scattering centers:

std::vector<fastjet::PseudoJet> scatteringCenters;

    // Find the scatteringCenters (i.e. recoil partons)

    for(fastjet::PseudoJet p : particlesMerged) {
         if (p.user_info<PU14>().vertex_number() == -1){ scatteringCenters.push_back(p);
         }
      }

Then apply the gridSubtractor
    gridSubtractor jewelSub(-1., -M_PI, 1., M_PI,0.4,0.05);
    std::vector<fastjet::PseudoJet> subtracted_particles =    jewelSub.doGridSub1(jetCollectionSig,scatteringCenters);
   fastjet::ClusterSequenceArea csSub(subtracted_particles, jet_def, area_def);
    jetCollection jetCollectionSub(sorted_by_pt(jet_selector(csSub.inclusive_jets(10.))));

The rest looks perfect

**Comment by mverwe** [comment]
A question: why is the input jets and not all particles in the event? I think this is dangerous since if a jet selection is done beforehand there might be holes in the particle distribution which will screw up the jet definition when you run the jet finder after the grid subtraction.

**Comment by aontoso** [comment]
I was just following the steps in the paper where they cluster and then do the discretization. What you are proposing is what they call Gridsub2 https://arxiv.org/pdf/1707.01539.pdf
They don’t see a strong difference between both of them but I can also write down the code where you use the whole event as input

Maybe @rkunnawa  has something to comment?

**Comment by aontoso** [comment]
Can anybody check why the information of the constituents cannot be accessed any longer when using “csSubtractor.hh”, for example? When I ran https://github.com/JetQuenchingTools/JetToyHI/blob/master/runCSVariations.cc
And do

trw.addCollection(Form("csJet_%d",ics), jetCollectionCSs[ics], true);

It doesn’t access the values of the constituents properties..This wasn’t the case a few months ago
On Jun 28, 2019, at 5:14 AM, Marta Verweij <notifications@github.com<mailto:notifications@github.com>> wrote:

A question: why is the input jets and not all particles in the event? I think this is dangerous since if a jet selection is done beforehand there might be holes in the particle distribution which will screw up the jet definition when you run the jet finder after the grid subtraction.

**Pull request merged**
